config/routes.rb
Rails.application.routes.draw do

  
  root "pages#home"
  resources :articles
  resources :users
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length:{minimum: 5, maximum:55}
    validates :description, presence: true, length:{minimum: 5, maximum:100}
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save {self.email = email.downcase}
    validates :username, presence:true, length: {minimum: 3, maximum:20},uniqueness: {case_sensitive: false}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  
  def index 
      @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def create
    #render plain: params[:article].inspect 
    @article  = Article.new(article_params)
    if @article.save
      flash[:notice] = "post added"
      redirect_to articles_path
    else 
      render "new"
      
    end
  end
  
  def show
    
  end
  
  def edit
   
  end
  
  def update
   
    if @article.update(article_params)
      flash[:notice] = "post updated"
      redirect_to article_path(@article)
    else
      render "edit"
    end
  end
  
  def destroy
     
     @article.destroy
     flash[:notice] = "Ой все ("
     redirect_to articles_path
  end
  
  private
  def article_params    
    params.require(:article).permit(:title, :description)
  end  
  
  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show,:edit,:update]
  
  def index
      # @user = currently
  end
  
  def new
    @user = User.new
  end
  def create
      #render plain: params[:user].inspect 
        @user = User.new(user_params)
        if @user.save
          flash[:notice] = "user created"
          redirect_to articles_path
        else 
          render "new"
        end
  end

  def show
    
  end
  
  def edit
   
  end
  
  def update
   
    if @user.update(user_params)
      flash[:notice] = "user information updated"
      redirect_to article_path
    else
      render "edit"
    end
  end 
  
  
  
  private
  def user_params    
    params.require(:user).permit(:username, :email)
  end 
  
  def set_user
    @user= User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
      <ul>
          <% @article.errors.full_messages.each do |msg| %>  
            <li><%= msg  %></li>
          <% end %>
      </ul
      >    
    <% end %>
<%= form_for @article do |f| %>
    <p class="center">
      <%= f.label :title %>
      
      <%= f.text_field :title, :class => 'answer' %>
    </p>
    <p class="center">
      <%= f.label :description %>
      <%= f.text_area :description, :class => 'answer-description' %>
      <br>
       <%=  f.submit "CREATE" , :class => "inverse-btn"%> 
    </p>
<%end%>

app/views/articles/edit.html.erb
<h1 class="text"><center> Edit Article </center><h1>
    
    <%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <%= image_tag "conect.png", width:"100%" %>
    </div>
   
  </div>
</div>
 <% @articles.each do |article| %>
     <div class="container ">
         <div class="row">
            <div class="col-md-6 col-md-push-3 panel panel-default padding-off">
           
                <div class="fon panel-heading">
                    
                    <b>by <%= article.user.username %></b>
                     
                </div>
                
                <div class="panel-body">
                    <b><%= article.title %></b><br>
                    <%= article.description %>
                </div>
                
                <div class="panel-footer fon">
                     <%= article.updated_at.strftime("%H:%M , %d-%m-%y") %>
                    
                <div class="footer-left">
                             <%= link_to "Look more", article_path(article) , :class => 'buttonstyle' %>
                             <%= link_to "Edit",edit_article_path(article) , :class => 'buttonstyle' %> 
                             <%= link_to "Delete", article_path(article) , :class => 'buttonstyle', method: :delete, data: {confirm: "А может нинада?" }%>
                </div>
                    
                </div>
                
                
            </div>
        </div>
    </div>
<% end %>

      

app/views/articles/new.html.erb
<div class="container down">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag "whats.png", width:"100%" %>
    </div>
    <div class="col-md-6 ">
                <h1 class="text"> <center> Create new article </center> <h1>
                <%= render 'form'  %>
    </div>    
    <div class="col-md-3">
        <%= image_tag "once.png", width:"110%" %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container ">
         <div class="row">
            <div class="col-md-6 col-md-push-3 panel panel-default padding-off">
           
                <div class="fon panel-heading">
                    
                    <b>by <%= @article.user.username %></b>
                     
                </div>
                
                <div class="panel-body">
                    <b><%= @article.title %></b><br>
                    <%= @article.description %>
                </div>
                
                <div class="panel-footer fon">
                     <%= @article.updated_at.strftime("%H:%M , %d-%m-%y") %>
                    
                <div class="footer-left">
                    <%= link_to "Back", articles_path , :class => 'buttonstyle' %>
                    <%= link_to "Edit", edit_article_path(@article) , :class => 'buttonstyle' %> 
                    <%= link_to "Delete", article_path , :class => 'buttonstyle', method: :delete, data: {confirm: "А может нинада?" }%>
                </div>
                    
                </div>
                
                
            </div>
        </div>
    </div>

<div class="container bottomfixing">
    <div class="row">
        <div class="col-md-12">
            <%= image_tag "look.png", width:'100%' %>
        </div>
    </div>  
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://blog-polinalen.c9users.io">URBLOG</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <form class="navbar-form navbar-left ">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "ALL POSTS",articles_path  %> </li> 
        <li><%=link_to "CREATE", new_article_path  %> </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Bahiana" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
</head>
<body class="bodyback">
  <%= render 'layouts/header' %>
  <ul>
  <% flash.each do |name, msg|%>
     <li> <%= msg %> </li> 
  <%end%>
  </ul>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
        <div class="container">
            <div class="row">
                
                <div class="col-md-5 col-md-push-4">
                     <a href="users/new"><%= image_tag "story.png", width:"100%" %> </a> 
                     <!--<= link_to "<%= image_tag "story.png", width:"100%" %>", new_user_path %> -->
                </div>
               
            </div>        
        </div>

app/views/users/_blank.html.erb
<% if @user.errors.any? %>
      <ul>
          <% @user.errors.full_messages.each do |msg| %>  
            <li><%= msg  %></li>
          <% end %>
      </ul
      >    
    <% end %>
<%= form_for @user do |f| %>
    <p class="center">
      <%= f.label :username %>
      
      <%= f.text_field :username, :class => 'answer' %>
    </p>
    <p class="center">
      <%= f.label :email %>
      <%= f.text_area :email, :class => 'answer-description' %>
      <br>
       <%=  f.submit "Sign up" , :class => "inverse-btn"%> 
       
    </p>
<%end%>

app/views/users/new.html.erb
<div class="container down">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag "user.png", width:"100%" %>
    </div>
    <div class="col-md-6 ">
                <h1 class="text"> <center> Registration </center> <h1>
                <%= render 'blank'  %>
    </div>    
    <div class="col-md-3">
        <%= image_tag "logo.png", width:"110%" %>
    </div>
  </div>
</div>